-- 1 에서  300  행에 대한 삽입 실패
--ORA-01722: invalid number
--행 1
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','surely', '확실히, 꼭','ad');
--행 2
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','setting', '무대 장치, 배경','n');
--행 3
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','servant', '하인','n');
--행 4
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','screen', '스크린, 화면','n');
--행 5
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','rainbow', '무지개','n');
--행 6
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','population', '인구','n');
--행 7
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','pool', '수영장의풀, 웅덩이','n');
--행 8
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','pilot', '파일럿, 비행기 조종사','n');
--행 9
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','peninsula', '반도','n');
--행 10
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','ox', '황소','n');
--행 11
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','opinion', '의견, 견해, 여론','n');
--행 12
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','oil', '기름, 석유','n');
--행 13
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','of', '~의, ~중의','prep');
--행 14
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','myth', '신화','n');
--행 15
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','mercy', '자비','n');
--행 16
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','meat', '식용의고기','n');
--행 17
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','Mars', '화성','n');
--행 18
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','mail', '우편물, 동','n');
--행 19
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','magic', '마술, 형','n');
--행 20
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','lip', '입술','n');
--행 21
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','lawyer', '변호사','n');
--행 22
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','journalism', '언론','n');
--행 23
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','joke', '농담, 동','n');
--행 24
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','handicapped', '장애가 있는','a');
--행 25
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','frog', '개구리','n');
--행 26
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','fantastic', '환상적인','a');
--행 27
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','equal', '같은, 동등한','a');
--행 28
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','allow', '허락하다','v');
--행 29
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','advise', '충고하다, 조언하다','v');
--행 30
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','add', '더하다, 덧붙여 말하다','v');
--행 31
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','worth', '가치가 있는, 명','a');
--행 32
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','without', '~없이, ~함 없이','prep');
--행 33
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','pond', '연못','n');
--행 34
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','hardly', '거의 ~않다','ad');
--행 35
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','develop', '발달시키다, 개발하다, 발전하다','v');
--행 36
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','depend', '의존하다, ~에 달려있다','v');
--행 37
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','continue', '계속하다','v');
--행 38
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','citizen', '시민','n');
--행 39
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','church', '교회','n');
--행 40
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','chimney', '굴뚝','n');
--행 41
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','champion', '챔피언, 우승자','n');
--행 42
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','case', '경우, 케이스','n');
--행 43
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','carpenter', '목수','n');
--행 44
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','candle', '양초','n');
--행 45
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','cafeteria', '카페테리아, 간이 식당','n');
--행 46
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','butterfly', '나비','n');
--행 47
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','businessman', '사업가, 실업가','n');
--행 48
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','bride', '신부','n');
--행 49
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','brick', '벽돌','n');
--행 50
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','bell', '종, 종소리','n');
--행 51
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','badminton', '배드민턴','n');
--행 52
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','automobile', '자동차','n');
--행 53
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','attendant', '시중드는 사람, 항공기 승무원','n');
--행 54
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','athlete', '운동선수','n');
--행 55
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','anxious', '걱정하는, 열망하는','a');
--행 56
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','anthem', '성가, 찬송가','n');
--행 57
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','ancient', '고대의, 옛날의','a');
--행 58
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','amount', '양, 총계, 동','n');
--행 59
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','album', '앨범, 사진첩','n');
--행 60
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','ability', '능력','n');
--행 61
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','proudly', '자랑스럽게','ad');
--행 62
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','protect', '보호하다','v');
--행 63
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','produce', '생산하다, 제작하다','v');
--행 64
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','path', '작은 길, 오솔길, 통로','n');
--행 65
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','over', '~위에, ~이상','prep');
--행 66
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','nest', '둥지, 보금자리','n');
--행 67
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','monument', '기념비, 기념탑, 기념물','n');
--행 68
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','minister', '목사, 장관','n');
--행 69
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','merchant', '상인','n');
--행 70
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','melt', '녹다, 녹이다','v');
--행 71
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','mask', '가면, 탈, 마스크','n');
--행 72
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','marriage', '결혼, 혼인','n');
--행 73
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','mailbox', '우편함, 우체통','n');
--행 74
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','liberty', '자유','n');
--행 75
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','laughter', '웃음, 웃음소리','n');
--행 76
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','key', '열쇠, 형','n');
--행 77
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','justice', '정의','n');
--행 78
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','jean', '청바지','n');
--행 79
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','invitation', '초대','n');
--행 80
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','instance', '예, 보기','n');
--행 81
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','industry', '공업, 산업, 근면','n');
--행 82
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','immigrant', '이민자','n');
--행 83
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','ill', '병든, 도덕적으로나쁜','a');
--행 84
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','hunger', '배고품, 굶주림','n');
--행 85
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','gym', '체육관, 체육','n');
--행 86
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','gray', '회색의, 백발이 섞인, 명','a');
--행 87
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','grave', '무덤','n');
--행 88
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','goods', '상품, 물품','n');
--행 89
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','fireman', '소방수','n');
--행 90
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','excellent', '우수한, 뛰어난','a');
--행 91
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','wake', '깨다, 깨우다','v');
--행 92
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','trash', '쓰레기','n');
--행 93
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','tragedy', '비극','n');
--행 94
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','topic', '화제, 주제','n');
--행 95
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','tongue', '혀, 말','n');
--행 96
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','textbook', '교과서','n');
--행 97
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','surface', '표면, 형','n');
--행 98
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','sunrise', '해돋이, 동틀녘','n');
--행 99
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','strictly', '엄격히','ad');
--행 100
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','spectator', '구경꾼, 관객','n');
--행 101
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','source', '원천, 근원, 출처','n');
--행 102
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','smog', '스모그','n');
--행 103
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','skill', '솜씨, 기능, 기술','n');
--행 104
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','sightseeing', '관광','n');
--행 105
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','sharp', '날카로운, 가파른','a');
--행 106
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','shame', '부끄러움, 수치','n');
--행 107
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','selfish', '이기적인','a');
--행 108
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','seed', '씨앗','n');
--행 109
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','score', '점수, 득점, 동','n');
--행 110
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','sandwich', '샌드위치','n');
--행 111
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','salty', '짠, 소금기 있는','a');
--행 112
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','rose', '장미','n');
--행 113
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','result', '결과, 동','n');
--행 114
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','reservation', '예약','n');
--행 115
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','record', '기록하다, 녹음녹화하다, 명','v');
--행 116
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','rat', '쥐','n');
--행 117
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','rabbit', '토끼','n');
--행 118
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','below', '~보다 아래에, ~이하에','prep');
--행 119
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','arrest', '체포하다, 명','v');
--행 120
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','apply', '적용하다, 지원하다','v');
--행 121
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','classical', '고전의, 고전적인','a');
--행 122
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','clap','손뼉을 치다','v');
--행 123
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','chew', '씹다','v');
--행 124
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','cheap', '싼','a');
--행 125
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','chalk', '분필','n');
--행 126
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','chain', '쇠사슬, 연쇄점','n');
--행 127
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','central', '중심의','a');
--행 128
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','cartoon', '만화, 만화영화','n');
--행 129
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','cap','모자, 뚜껑','n');
--행 130
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','campaign', '캠페인, 운동','n');
--행 131
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','bush', '관목, 덤불, 수풀','n');
--행 132
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','burden', '무거운 짐, 부담, 동','n');
--행 133
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','bubble', '거품, 동','n');
--행 134
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','bore', '지루하게 하다','v');
--행 135
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','border', '가장자리, 경계, 국경','n');
--행 136
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','bookstore', '서점','n');
--행 137
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','biography', '전기, 일대기','n');
--행 138
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','besides', '게다가, 그 밖에, 전치사','ad');
--행 139
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','bench', '벤치, 긴 의자2인용이상','n');
--행 140
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','belt', '벨트, 띠','n');
--행 141
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','beef', '쇠고기','n');
--행 142
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','bedroom', '침실','n');
--행 143
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','beauty', '아름다움, 미인','n');
--행 144
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','bath', '목욕','n');
--행 145
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','basket', '바구니','n');
--행 146
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','base', '기초, 야구베이스','n');
--행 147
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','Atlantic', '대서양, 형','n');
--행 148
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','around', '~의 주위에','prep');
--행 149
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','April', '4월','n');
--행 150
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','advance', '전진시키다, 나아가다, 명','v');
--행 151
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','fog', '안개','n');
--행 152
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','female', '여성, 암컷, 형','n');
--행 153
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','fellow', '사람, 동료, 형','n');
--행 154
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','fault', '잘못, 결점','n');
--행 155
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','faint', '희미한, 어질어질한','a');
--행 156
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','experience', '경험, 동','n');
--행 157
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','equipment', '장비, 설비','n');
--행 158
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','entrance', '입구, 들어감','n');
--행 159
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','engine', '엔진, 기관차, 소방차','n');
--행 160
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','endurance', '인내, 지구력, 내구성','n');
--행 161
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','elevator', '엘리베이터, 승강기','n');
--행 162
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','elephant', '코끼리','n');
--행 163
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','dump', '쓰레기를내버리다, 동','v');
--행 164
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','duck', '오리','n');
--행 165
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','discover', '발견하다','v');
--행 166
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','disappoint', '실망시키다','v');
--행 167
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','disappear', '사라지다','v');
--행 168
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','directly', '곧장, 직접, 즉시','ad');
--행 169
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','difficulty', '어려움, 곤경','n');
--행 170
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','differ', '다르다','v');
--행 171
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','dictionary', '사전','n');
--행 172
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','diamond', '다이아몬드','n');
--행 173
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','devil', '악마','n');
--행 174
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','dessert', '디저트, 후식','n');
--행 175
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','desert', '사막, 동','n');
--행 176
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','degree', '정도, 등급, 각도,온도의도, 학위','n');
--행 177
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','cream', '크림','n');
--행 178
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','Christian', '기독교인, 형','n');
--행 179
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','behind', '~의 뒤에','prep');
--행 180
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','asleep', '잠들어','a');
--행 181
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','flow', '흐르다, 명','v');
--행 182
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','freeze', '얼다, 얼게 하다','v');
--행 183
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','greet', '인사하다','v');
--행 184
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','hang', '걸다, 매달다, 매달리다','v');
--행 185
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','item', '항목, 품목','n');
--행 186
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','jail', '교도소, 감옥','n');
--행 187
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','jam', '잼, 혼잡','n');
--행 188
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','jewel', '보석','n');
--행 189
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','knee', '무릎','n');
--행 190
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','knowledge', '지식','n');
--행 191
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','lamb', '새끼 양','n');
--행 192
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','lamp', '램프, 등불','n');
--행 193
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','leather', '가죽, 형','n');
--행 194
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','lunar', '달의','a');
--행 195
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','lung', '폐, 허파','n');
--행 196
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','match', '성냥, 시합, 동','n');
--행 197
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','medical', '의학의, 의료의','a');
--행 198
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','mild', '부드러운, 온화한','a');
--행 199
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','napkin', '냅킨','n');
--행 200
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','navy', '해군','n');
--행 201
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','near', '~가까이에','prep');
--행 202
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','neck', '목','n');
--행 203
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','nephew', '조카','n');
--행 204
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','nonsense', '무의미한 말, 허튼 소리, 터무니없는 것','n');
--행 205
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','nose', '코','n');
--행 206
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','otherwise', '달리, 그렇지 않으면','ad');
--행 207
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','pants', '바지','n');
--행 208
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','passenger', '승객','n');
--행 209
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','photo', '사진','n');
--행 210
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','plate', '접시','n');
--행 211
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','voyage', '여행, 항해, 동','n');
--행 212
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','volleyball', '배구','n');
--행 213
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','valley', '골짜기, 계곡','n');
--행 214
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','universe', '우주, 삼라만상','n');
--행 215
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','Tuesday', '화요일','n');
--행 216
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','tooth', '이, 치아','n');
--행 217
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','title', '제목, 직함, 스포츠 타이트','n');
--행 218
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','tightly', '단단히, 꽉','ad');
--행 219
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','through', '~을 뚫고, ~을 통과하여','prep');
--행 220
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','theater', '극장, 연극','n');
--행 221
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','suit', '한 벌 정장, 동','n');
--행 222
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','storm', '폭풍우','n');
--행 223
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','stage', '무대, 단계','n');
--행 224
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','slope', '경사지, 비탈','n');
--행 225
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','scientific', '과학의, 과학적인','a');
--행 226
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','rent', '임대료, 동','n');
--행 227
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','recycle', '재활용하다','v');
--행 228
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','print', '인쇄물, 동','n');
--행 229
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','prepare', '준비하다','v');
--행 230
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','powerful', '강력한','a');
--행 231
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','peaceful', '평화스러운','a');
--행 232
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','painful', '아픈, 고통을 주는','a');
--행 233
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','pain', '고통, 수고, 노고','n');
--행 234
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','pack', '꾸러미, 동','n');
--행 235
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','organization', '조직, 단체','n');
--행 236
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','master', '주인, 대가, 동','n');
--행 237
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','jacket', '재킷, 양복의 상의','n');
--행 238
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','dentist', '치과 의사','n');
--행 239
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','communicate', '정보 등을전달하다, 의사소통 하다','v');
--행 240
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','argue', '논쟁하다, 주장하다','v');
--행 241
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','widely', '넓게, 크게','ad');
--행 242
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','wealthy', '부유한','a');
--행 243
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','waist', '허리','n');
--행 244
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','useless', '쓸모없는, 무익한','a');
--행 245
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','tomb', '무덤','n');
--행 246
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','ticket', '티켓, 표','n');
--행 247
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','tax', '세금','n');
--행 248
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','taste', '맛보다, ~의 맛이나다, 명','v');
--행 249
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','sting', '찌르다','v');
--행 250
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','starve', '굶어 죽다, 굶주리다','v');
--행 251
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','spoil', '망치다','v');
--행 252
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','sore', '아픈, 쑤시는','a');
--행 253
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','sob', '흐느껴 울다, 명','v');
--행 254
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','shock', '쇼크, 충격, 동','n');
--행 255
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','search', '찾다, 탐색하다, 명','v');
--행 256
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','satellite', '인공위성, 형','n');
--행 257
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','rush', '돌진하다, 서두르다, 명','v');
--행 258
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','root', '뿌리','n');
--행 259
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','role', '역할','n');
--행 260
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','purpose', '목적','n');
--행 261
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','post', '기둥, 지위, 우편물, 동','n');
--행 262
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','position', '위치, 지위','n');
--행 263
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','Olympic', '올림픽의, 명','a');
--행 264
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','form', '형태, 동','n');
--행 265
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','flame', '불꽃, 동','n');
--행 266
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','deal', '다루다, 거래하다, 명','n');
--행 267
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','bone', '뼈','n');
--행 268
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','attack', '공격하다, 명','v');
--행 269
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','among', '~3개 이상의사이에, ~중의 하나로','prep');
--행 270
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','adult', '어른, 성인, 형','n');
--행 271
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','wealth ', '부, 재산','n');
--행 272
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','view', '보기, 경치, 견해, 동','n');
--행 273
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','tough', '강인한, 질긴, 힘든','a');
--행 274
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','total', '총계의, 전체의, 명','a');
--행 275
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','thirsty', '목마른','a');
--행 276
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','teenager', '십대','n');
--행 277
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','tail', '꼬리','n');
--행 278
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','structure', '구조물','n');
--행 279
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','stream', '흐름, 시내','n');
--행 280
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','stick', '막대기, 찌르다, 붙이다, 달라붙다','n');
--행 281
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','spell', '철자를 쓰다','v');
--행 282
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','sort', '종류','n');
--행 283
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','shell', '껍질, 조개','n');
--행 284
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','serve', '섬기다, 봉사하다, 시중들다','v');
--행 285
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','schedule', '예정표, 동','n');
--행 286
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','rough', '거칠거칠한, 거친, 대략의','a');
--행 287
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','punish', '벌주다','v');
--행 288
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','pet', '애완동물, 형','n');
--행 289
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','parcel', '소포','n');
--행 290
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','observe', '관찰하다, 규칙 등을준수하다','v');
--행 291
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','native', '출생지의, 토착의, 명','a');
--행 292
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','mirror', '거울','n');
--행 293
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','ignore', '무시하다','v');
--행 294
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','furniture', '가구','n');
--행 295
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','export', '수출하다, 명','v');
--행 296
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','envelope', '봉투','n');
--행 297
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','clever', '영리한','a');
--행 298
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','bomb', '폭탄, 동','n');
--행 299
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','awfully', '아주, 몹시','ad');
--행 300
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'M','shoulder','어깨','n');
