-----------------------------------MEMBER-----------------------------------

    DROP TABLE MEMBER;
    SELECT*FROM MEMBER;

  --테이블 생성
    CREATE TABLE MEMBER(
    USER_NO NUMBER NOT NULL PRIMARY KEY,           --시퀀스 -> 'USER_NO_SEQ'
    USER_ID VARCHAR2(50) NOT NULL UNIQUE,                     
    PASSWORD VARCHAR2(50) NOT NULL,
    NICKNAME VARCHAR2(50) NOT NULL UNIQUE,
    POINTS NUMBER DEFAULT 0 NOT NULL
);

--test user (USER_NO_SEQ @ 1)
INSERT INTO MEMBER VALUES(USER_NO_SEQ.nextval, 'test', 'test', 'TEST', 0);
--admin (USER_NO_SEQ @ 2)
INSERT INTO MEMBER VALUES(USER_NO_SEQ.nextval, 'admin', 'admin', 'ADMIN', 0);
INSERT INTO ADMIN VALUES(2);


--시퀀스 생성 (유저넘버 시퀀스)
    DROP SEQUENCE USER_NO_SEQ;
    
    CREATE SEQUENCE USER_NO_SEQ   
    START WITH 1
    NOCYCLE
    NOMAXVALUE;


    
--코멘트
    COMMENT ON TABLE MEMBER IS ' 회원정보 테이블';
    COMMENT ON COLUMN MEMBER.USER_NO IS '유저넘버';
    COMMENT ON COLUMN MEMBER.USER_ID IS '아이디';
    COMMENT ON COLUMN MEMBER.PASSWORD IS '비밀번호';
    COMMENT ON COLUMN MEMBER.NICKNAME IS '닉네임';

------------------------- ADMIN -----------------------------

DROP TABLE ADMIN;
SELECT*FROM ADMIN;

--테이블 생성
CREATE TABLE ADMIN AS
SELECT USER_NO FROM MEMBER;          -- 시퀀스 -> 'USER_NO_SEQ'

--코멘트
COMMENT ON TABLE ADMIN IS ' 관리자 테이블';
COMMENT ON COLUMN ADMIN.USER_NO IS '번호';

-----------------------------WORD-----------------------------
DROP TABLE WORD;
DELETE FROM WORD;
SELECT*FROM WORD;

--테이블 생성
CREATE TABLE WORD( 
    WORD_NO NUMBER NOT NULL PRIMARY KEY,                    --시퀀스 -> 'WORD_NO_SEQ' 
    WORD_LEVEL VARCHAR2(1) NOT NULL,
    WORD_ENG VARCHAR2(128) NOT NULL,
    WORD_KOR VARCHAR2(128) NOT NULL,
    WORD_PART VARCHAR2(10) NOT NULL
    );

--시퀀스 생성
    DROP SEQUENCE WORD_NO_SEQ;

    CREATE SEQUENCE WORD_NO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE;


--코멘트
COMMENT ON TABLE WORD IS ' 개인 영어단어 테이블';
COMMENT ON COLUMN WORD.WORD_NO IS '단어 번호';
COMMENT ON COLUMN WORD.WORD_LEVEL IS '단어 레벨(H:상 , M:중 , L:하)';
COMMENT ON COLUMN WORD.WORD_ENG IS '영어단어';
COMMENT ON COLUMN WORD.WORD_KOR IS '개인 한글뜻';
COMMENT ON COLUMN WORD.WORD_PART IS '품사';

-----------------------------------USER_WORD------------------------------

DROP TABLE USER_WORD;
SELECT*FROM USER_WORD;

--테이블 생성
CREATE TABLE USER_WORD AS
SELECT USER_NO FROM MEMBER;              --시퀀스 -> 'USER_NO_SEQ'

ALTER TABLE USER_WORD ADD USER_WORD_NO NUMBER NOT NULL PRIMARY KEY;      -- 시퀀스-> 'WORD_NO_SEQ'
ALTER TABLE USER_WORD ADD USER_WORD_LEVEL VARCHAR2(1) NOT NULL;
ALTER TABLE USER_WORD ADD USER_ENG VARCHAR2(50) NOT NULL;
ALTER TABLE USER_WORD ADD USER_KOR VARCHAR2(50) NOT NULL;
ALTER TABLE USER_WORD ADD USER_PART VARCHAR2(10) NOT NULL;


--코멘트
COMMENT ON TABLE USER_WORD IS ' 개인 영어단어 테이블';
COMMENT ON COLUMN USER_WORD.USER_NO IS '유저 번호';
COMMENT ON COLUMN USER_WORD.USER_WORD_NO IS '개인 단어 번호';
COMMENT ON COLUMN USER_WORD.USER_WORD_LEVEL IS '개인 단어 레벨(H:상 , M:중 , L:하)';
COMMENT ON COLUMN USER_WORD.USER_ENG IS '개인 단어';
COMMENT ON COLUMN USER_WORD.USER_KOR IS '개인 한글뜻';
COMMENT ON COLUMN USER_WORD.USER_PART IS '개인 단어 품사';

-----------------------------------TEST -----------------------------------

DROP TABLE TEST;
SELECT*FROM TEST;

--테이블 생성
CREATE TABLE TEST AS
SELECT USER_NO FROM MEMBER;              --시퀀스 -> 'USER_NO_SEQ'

ALTER TABLE TEST ADD TEST_ROUND NUMBER NOT NULL;
ALTER TABLE TEST ADD TEST_DATE VARCHAR2(20) NOT NULL;
ALTER TABLE TEST ADD TEST_LEVEL VARCHAR2(1) NOT NULL;
ALTER TABLE TEST ADD CORRECT_NUMBER NUMBER;
ALTER TABLE TEST ADD WRONG_NUMBER NUMBER;
ALTER TABLE TEST ADD WRONG_WORD VARCHAR2(100);


--코멘트
COMMENT ON TABLE TEST IS '시험정보 테이블';
COMMENT ON COLUMN TEST.USER_NO IS '번호';
COMMENT ON COLUMN TEST.TEST_ROUND IS '시험회차';
COMMENT ON COLUMN TEST.TEST_DATE IS '영단어';
COMMENT ON COLUMN TEST.CORRECT_NUMBER IS '정답갯수';
COMMENT ON COLUMN TEST.WRONG_NUMBER IS '오답갯수';
COMMENT ON COLUMN TEST.WRONG_WORD IS '틀린 단어';



--------------------------------------------------------------------------------
select * from member;
select * from admin;
select * from user_word;
select * from test;
select * from word;
