-- 1 에서  300  행에 대한 삽입 실패
--ORA-01722: invalid number
--행 1
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','world', '세계, 세상','n');
--행 2
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','way', '길, 방법','n');
--행 3
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','very', '매우','ad');
--행 4
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','today', '오늘날, 부','n');
--행 5
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','time', '시간, 시각','n');
--행 6
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','this', '이것, 이 사람,  형','n');
--행 7
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','thing', '물건, 일, 것','n');
--행 8
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','there', '그곳에, 거기에','ad');
--행 9
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','bother','괴롭히다, 귀찮게 하다','v');
--행 10
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','that', '저것, 저 사람, 형','n');
--행 11
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','some', '일부 사람것들, 형','n');
--행 12
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','school', '학교','n');
--행 13
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','say', '말하다','v');
--행 14
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','people', '사람들, 민족, 국민','n');
--행 15
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','name', '이름, 동','n');
--행 16
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','much', '양이많은, 부','a');
--행 17
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','mother', '어머니','n');
--행 18
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','morning', '아침, 오전','n');
--행 19
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','many', '수가많은, 명','a');
--행 20
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','man', '남자, 사람','n');
--행 21
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','like', '좋아하다, 바라다','v');
--행 22
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','lesson', '교과서의 과, 수업, 교훈','n');
--행 23
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','house', '집','n');
--행 24
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','home', '자기 집, 가정, 부','n');
--행 25
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','have', '가지고 있다, 먹다, ~하게 하다','v');
--행 26
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','good', '좋은, 잘하는','a');
--행 27
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','father', '아버지','n');
--행 28
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','dialog', '대화','n');
--행 29
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','day', '낮, 하루, 날','n');
--행 30
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','all', '모두, 형','n');
--행 31
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','big', '큰','a');
--행 32
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','birthday', '생일','n');
--행 33
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','book', '책','n');
--행 34
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','brother', '남자 형제','n');
--행 35
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','child', '어린이, 자식','n');
--행 36
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','city', '도시','n');
--행 37
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','do', '~하다','v');
--행 38
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','dog', '개','n');
--행 39
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','earth', '지구, 땅, 흙','n');
--행 40
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','farmer', '농부','n');
--행 41
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','food', '식량, 먹을 것, 식품','n');
--행 42
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','future', '미래, 장래, 형','n');
--행 43
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','game', '게임, 경기','n');
--행 44
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','happy', '행복한, 기쁜','a');
--행 45
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','help', '돕다, 명','v');
--행 46
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','know', '알다','v');
--행 47
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','life', '생명, 인생, 생활','n');
--행 48
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','look', '보다, ~처럼 보이다 ','n');
--행 49
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','love', '사랑, 동','n');
--행 50
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','nice', '좋은, 멋진, 친절한','a');
--행 51
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','night', '밤, 형','n');
--행 52
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','place', '장소','n');
--행 53
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','room', '방, 공간','n');
--행 54
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','sea', '바다','n');
--행 55
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','student', '학생','n');
--행 56
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','sun', '태양, 햇빛','n');
--행 57
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','tomorrow', '내일','n');
--행 58
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','up', '위로, 위의','ad');
--행 59
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','well', '잘, 명','ad');
--행 60
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','woman', '여자, 여성','n');
--행 61
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','afternoon', '오후','n');
--행 62
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','also', '또한','ad');
--행 63
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','animal', '동물','n');
--행 64
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','any', '어떤, 명','a');
--행 65
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','bus', '버스','n');
--행 66
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','computer', '컴퓨터','n');
--행 67
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','different', '다른','a');
--행 68
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','dinner', '저녁 식사','n');
--행 69
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','down', '아래로','ad');
--행 70
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','fish', '물고기, 동','n');
--행 71
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','fun', '장난, 재미','n');
--행 72
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','girl', '소녀','n');
--행 73
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','hand', '손, 동','n');
--행 74
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','hard', '힘든, 굳은, 부','a');
--행 75
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','job', '일, 직업','n');
--행 76
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','letter', '편지, 글자, 문자','n');
--행 77
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','lunch', '점심 식사','n');
--행 78
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','make', '만들다, 시키다','v');
--행 79
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','music', '음악','n');
--행 80
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','picture', '그림, 사진','n');
--행 81
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','question', '물음, 의문, 문제','n');
--행 82
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','really', '정말로','ad');
--행 83
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','sport', '스포츠, 운동','n');
--행 84
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','street', '거리, 도로','n');
--행 85
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','tell', '말하다','v');
--행 86
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','watch', '손목시계, 동','n');
--행 87
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','weather', '날씨','n');
--행 88
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','week', '주, 주간','n');
--행 89
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','work', '일하다, 공부하다, 명','v');
--행 90
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','you', '너는, 너희들은, 너를, 너희들을','n');
--행 91
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','always', '늘, 언제나','ad');
--행 92
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','answer', '대답, 동','n');
--행 93
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','ask', '요청하다, 부탁하다','v');
--행 94
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','away', '떨어져, 떠나서','ad');
--행 95
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','baseball', '야구','n');
--행 96
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','bed', '침대','n');
--행 97
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','brown', '갈색의, 명','a');
--행 98
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','course', '진행, 진로, 코스','n');
--행 99
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','each', '각각의, 명','a');
--행 100
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','evening', '저녁','n');
--행 101
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','farm', '농장','n');
--행 102
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','fine', '좋은, 훌륭한, 명','a');
--행 103
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','give', '주다','v');
--행 104
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','grandfather', '할아버지','n');
--행 105
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','homework', '숙제','n');
--행 106
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','keep', '보존하다, 유지하다, 계속하다','v');
--행 107
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','mountain', '산','n');
--행 108
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','park', '공원, 동','n');
--행 109
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','pen', '펜','n');
--행 110
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','prince', '왕자','n');
--행 111
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','problem', '문제','n');
--행 112
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','river', '강','n');
--행 113
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','rule', '규칙, 지배, 동','n');
--행 114
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','summer', '여름','n');
--행 115
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','table', '탁자','n');
--행 116
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','tennis', '테니스','n');
--행 117
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','tree', '나무','n');
--행 118
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','uncle', '아저씨, 삼촌, 고모부, 이보무, 숙부','n');
--행 119
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','we', '우리가, 우리는','n');
--행 120
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','word', '단어, 말','n');
--행 121
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','wife', '아내','n');
--행 122
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','town', '마을','n');
--행 123
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','Sunday', '일요일','n');
--행 124
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','south', '남쪽,  형','n');
--행 125
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','song', '노래','n');
--행 126
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','sky', '하늘','n');
--행 127
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','Saturday', '토요일','n');
--행 128
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','run', '달리다, 운영하다','v');
--행 129
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','party', '파티, 모임','n');
--행 130
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','oneself', '자기 자신, 자기 스스로','n');
--행 131
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','once', '한번, 이전에, 접속사','ad');
--행 132
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','number', '수, 번호','n');
--행 133
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','newspaper', '신문','n');
--행 134
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','mouse', '쥐  복수형','n');
--행 135
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','land', ' 육지, 땅, 나라, 동','n');
--행 136
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','hour', '한 시간, 시','n');
--행 137
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','hot', '뜨거운, 더운, 매운','a');
--행 138
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','history', '역사','n');
--행 139
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','high', '높은, 비싼,  부','a');
--행 140
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','hear', '듣다','v');
--행 141
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','gold', '금,  형','n');
--행 142
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','glad', '기쁜','a');
--행 143
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','flower', '꽃','n');
--행 144
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','even', '~조차, 비교급 강조 더욱, 훨씬','ad');
--행 145
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','donkey', '당나귀','n');
--행 146
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','change', '바꾸다, 명','v');
--행 147
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','building', '빌딩, 건물','n');
--행 148
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','bike', '자전거','n');
--행 149
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','become', '~이 되다','v');
--행 150
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','baby', '갓난 아이, 아기','n');
--행 151
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','white', '흰색의, 명','a');
--행 152
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','waste', '쓰레기, 낭비, 동','n');
--행 153
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','tower', '탑, 타워','n');
--행 154
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','team', '팀, 조','n');
--행 155
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','store', '가게, 상점','n');
--행 156
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','stone', '돌,  형','n');
--행 157
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','still', '조용한, 부','a');
--행 158
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','shoe', '구두, 신발','n');
--행 159
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','season', '계절, 철','n');
--행 160
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','race', '경기, 인종, 종족, 동','n');
--행 161
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','pollution', '오염','n');
--행 162
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','piece', '조각','n');
--행 163
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','mind', '마음, 동','n');
--행 164
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','maybe', '어쩌면, 아마도','ad');
--행 165
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','matter', '문제, 물질, 동','n');
--행 166
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','manner', '태도, 방법','n');
--행 167
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','line', '선, 줄 글자의행, 동','n');
--행 168
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','few', '거의 없는','a');
--행 169
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','everbody', '누구나, 모두','n');
--행 170
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','driver', '운전하는 사람','n');
--행 171
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','dress', '옷, 드레스, 동','n');
--행 172
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','desk', '책상','n');
--행 173
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','daughter', '딸','n');
--행 174
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','clean', '깨끗한, 동','a');
--행 175
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','call', '부르다,전화하다, 명','v');
--행 176
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','cake', '케이크','n');
--행 177
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','buy', '구입하다, 사다','v');
--행 178
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','ball', '공','n');
--행 179
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','bag', '가방','n');
--행 180
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','ago', '~전에','ad');
--행 181
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','will', '~할 것이다','v');
--행 182
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','war', '전쟁','n');
--행 183
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','tall', '키가 큰','a');
--행 184
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','ship ', ' 배','n');
--행 185
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','sad', '슬픈','a');
--행 186
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','rice', '쌀, 벼','n');
--행 187
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','nature', '자연, 천성','n');
--행 188
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','month', '달력의 달, 월','n');
--행 189
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','library', '도서관','n');
--행 190
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','leaf', '잎','n');
--행 191
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','kitchen', '부엌','n');
--행 192
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','however', '그러나, 아무리 ~해도','ad');
--행 193
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','health', '건강','n');
--행 194
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','head', '머리','n');
--행 195
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','grandparent', '조부모','n');
--행 196
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','grandmother', '할머니','n');
--행 197
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','gesture', '몸짓, 제스쳐','n');
--행 198
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','fire', '불, 화재','n');
--행 199
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','feel', '느끼다','n');
--행 200
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','fast', '빠른, 단단한, 부','a');
--행 201
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','end', '끝, 동','n');
--행 202
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','color', '색, 빛깔','n');
--행 203
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','cat', '고양이','n');
--행 204
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','card', '카드','n');
--행 205
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','breakfast ', '아침식사','n');
--행 206
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','believe', '믿다, ~라고 생각하다','v');
--행 207
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','begin', '시작하다','n');
--행 208
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','basketball', '농구, 농구공','n');
--행 209
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','apple', '사과','n');
--행 210
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','already', '이미, 벌써','ad');
--행 211
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','alphabet', '알파벳, 자음모음','n');
--행 212
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','bring', '가져오다, 데려오다','v');
--행 213
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','chance', '기회, 가망','n');
--행 214
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','cross', '건나다, 교차시키다, 명','v');
--행 215
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','custom', '관습, 풍속','n');
--행 216
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','floor', '바닥, 건물의층','n');
--행 217
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','garden', '뜰, 정원','n');
--행 218
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','glass', '유리, 유리컵','n');
--행 219
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','god', '신, 조물주','n');
--행 220
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','hammer', '망치','n');
--행 221
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','hotel', '호텔','n');
--행 222
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','may', '~해도 좋다, ~일지도 모른다','v');
--행 223
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','milk', '우유','n');
--행 224
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','nail', '손톱, 발톱, 못','n');
--행 225
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','noise', '소음, 시끄러운 소리','n');
--행 226
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','officer', '장교, 공무원, 순경','n');
--행 227
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','phone', '전화기, 동','n');
--행 228
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','police', '경찰','n');
--행 229
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','poor', '가난한, 불쌍한, 서투른','a');
--행 230
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','rather', '오히려, 다소','ad');
--행 231
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','ready', '준비된','a');
--행 232
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','red', '붉은, 빨간색의, 명','a');
--행 233
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','size', '크기, 치수, 사이즈','n');
--행 234
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','smile', '미소짓다, 명','v');
--행 235
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','someday', '미래의언젠가','ad');
--행 236
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','traffic', '교통량','n');
--행 237
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','treasure', '보물','n');
--행 238
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','turn', '돌리다, ~이 되다, 명','v');
--행 239
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','visit', '방문하다, 명','v');
--행 240
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','waiter', '웨이터, 시중드는 사람','n');
--행 241
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','truth', '진실, 진리','n');
--행 242
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','trouble', '곤란, 걱정거리, 동','n');
--행 243
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','top', '꼭대기, 정상, 팽이, 형','n');
--행 244
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','tea', '마시는차','n');
--행 245
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','station', '역, 정거장, 부서','n');
--행 246
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','sit', '앉다','v');
--행 247
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','scientist', '과학자','n');
--행 248
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','road', '길, 도로','n');
--행 249
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','practice', '연습, 실행, 동','n');
--행 250
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','picnic', '소풍','n');
--행 251
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','ought to', '~해야 한다, ~임에 틀림없다','v');
--행 252
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','moment', '순간, 때','n');
--행 253
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','meal', '식사','n');
--행 254
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','lose', '잃다, 지다','v');
--행 255
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','ice', '얼음, 영국아이스크림','n');
--행 256
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','holiday', '휴일','n');
--행 257
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','half', '절반, 대','n');
--행 258
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','grow', '자라다, 기르다, ~이 되다','v');
--행 259
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','glory', '영광','n');
--행 260
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','fruit', '과일','n');
--행 261
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','football', '축구','n');
--행 262
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','favorite', '가장 좋아하는, 명','a');
--행 263
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','fall', '가을, 폭포, 동','n');
--행 264
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','egg', '계란, 달걀','n');
--행 265
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','dirty', '더러운','a');
--행 266
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','difficult', '어려운','a');
--행 267
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','carefully', '주의 깊게','ad');
--행 268
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','box', '상자','n');
--행 269
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','bear', '낳다, 견디다, 명','v');
--행 270
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','airplane', '비행기','n');
--행 271
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','and', '그리고','conj');
--행 272
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','bread', '빵','n');
--행 273
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','bridge', '건너는 다리','n');
--행 274
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','capital', '수도, 대문자, 자본, 형','n');
--행 275
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','dinosaur', '공룡','n');
--행 276
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','doll', '인형','n');
--행 277
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','drink', '마시다, 명','v');
--행 278
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','energy', '에너지, 정력, 힘','n');
--행 279
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','fact', '사실','n');
--행 280
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','foot', '발 복수형','n');
--행 281
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','gas', '가스, 미국휘발류','n');
--행 282
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','habit', '습관','n');
--행 283
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','hair', '머리카락, 털','n');
--행 284
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','machine', '기계','n');
--행 285
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','marathon', '마라톤','n');
--행 286
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','Monday', '월요일','n');
--행 287
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','piano', '피아노','n');
--행 288
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','plan', '계획, 동','n');
--행 289
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','program', '프로그램, 진행 순서, 계획','n');
--행 290
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','quite', '아주, 꽤','ad');
--행 291
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','rock', '바위, 동','n');
--행 292
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','rope', '로프, 밧줄, 끈','n');
--행 293
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','safe', '안전한','a');
--행 294
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','sale', '판매, 할인 판매','n');
--행 295
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','sleep', '자다, 명','v');
--행 296
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','soup', '수프','n');
--행 297
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','strange', '이상한, 낯선','a');
--행 298
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','teach', '가르치다','v');
--행 299
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','wear', '입다, 신다, 쓰다, 명','v');
--행 300
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'L','wise', '슬기로운, 현명한','a');
