-- 1 에서  348  행에 대한 삽입 실패
--ORA-01722: invalid number
--행 1
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','require','필요로하다','v');
--행 2
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','requisite','필수의','a');
--행 3
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','requirement','필요,요구','n');
--행 4
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','technology','과학기술','n');
--행 5
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','technologist','과학,기술자','n');
--행 6
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','individual','개인','n');
--행 7
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','individuality','개성','n');
--행 8
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','individualism','개인주의','n');
--행 9
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','provide','공급하다,준비하다','v');
--행 10
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','provided','만일～라면','conj');
--행 11
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','provision','공급,규정','n');
--행 12
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','object','대상,물체','n');
--행 13
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','objection','반대','n');
--행 14
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','objective','목적','n');
--행 15
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','objectively','객관적으로','ad');
--행 16
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','nonobjective','비객관적인,추상적인','a');
--행 17
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','level','평면,수준','n');
--행 18
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','level-headed','온건한,냉정한','a');
--행 19
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','involve','싸다,연루시키다','v');
--행 20
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','employ','고용하다','v');
--행 21
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','employee','종업원','n');
--행 22
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','employer','고용주','n');
--행 23
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','unemployment','실업','n');
--행 24
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','attitude','태도','n');
--행 25
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','improve','개선하다','v');
--행 26
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','improvement','개선','n');
--행 27
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','research','조사','n');
--행 28
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','researcher','조사원','n');
--행 29
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','supply','공급하다','v');
--행 30
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','tend','～하는경향이있다','v');
--행 31
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','tendency','경향','n');
--행 32
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','affect','영향을미치다','v');
--행 33
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','affection','영향,애정','n');
--행 34
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','affectionate','애정깊은','a');
--행 35
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','thus','따라서','ad');
--행 36
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','benefit','이익','n');
--행 37
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','beneficial','유익한','a');
--행 38
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','beneficiary','수익자','n');
--행 39
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','demand','요구하다','v');
--행 40
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','occasion','경우','n');
--행 41
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','occasional','이따금의','a');
--행 42
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','fashion','유행','n');
--행 43
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','fashionable','유행의','a');
--행 44
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','recognize','인식하다','v');
--행 45
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','recognition','인식','n');
--행 46
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','unrecognized','인식되지않은','a');
--행 47
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','proper','적당한','a');
--행 48
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','properly','적당히','ad');
--행 49
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','propriety','적당','n');
--행 50
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','property','재산','n');
--행 51
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','due','지불기일이된～예정인','a');
--행 52
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','overdue','지불기한이넘은','a');
--행 53
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','behave','제대로행동하다','v');
--행 54
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','behavior','행동','n');
--행 55
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','opportunity','기회','n');
--행 56
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','determine','결정하다','v');
--행 57
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','determination','결정','n');
--행 58
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','predetermine','미리결정하다','v');
--행 59
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','generate','발생시키다','v');
--행 60
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','generator','발전기','n');
--행 61
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','generation','산출세대','n');
--행 62
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','exist','존재하다','v');
--행 63
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','existence','존재','n');
--행 64
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','existentialism','실존주의','n');
--행 65
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','existent','존재하는','a');
--행 66
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','coexistence','공존','n');
--행 67
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','nonexistent','존재하지않는','a');
--행 68
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','regret','후회','n');
--행 69
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','regretful','후회하는','a');
--행 70
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','regrettable','슬픈,가엾은','a');
--행 71
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','occur','발생하다','v');
--행 72
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','occurrence','발생','n');
--행 73
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','available','쓸모있는','a');
--행 74
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','avail','쓸모있다','v');
--행 75
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','professional','전문적인','a');
--행 76
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','profession','전문직','n');
--행 77
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','profess','직업으로하다','v');
--행 78
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','frequent','빈번한','a');
--행 79
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','contact','접촉','n');
--행 80
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','respond','반응하다','v');
--행 81
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','response','반응','n');
--행 82
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','respondent','응답자','n');
--행 83
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','responsive','반응의','a');
--행 84
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','emotional','감동적인','a');
--행 85
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','diet','식이요법','n');
--행 86
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','severe','엄격한,맹렬한','a');
--행 87
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','severity','엄격함,맹렬함','n');
--행 88
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','gloom','어둑어둑함,우울함','n');
--행 89
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','gloomy','어둑한,우울한','a');
--행 90
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','negative','부정적인','a');
--행 91
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','negation','부정','n');
--행 92
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','victim','희생','n');
--행 93
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','biology','생물학','n');
--행 94
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','biologist','생물학자','n');
--행 95
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','biochemistry','생화학','n');
--행 96
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','biomechanical','생물역학의','a');
--행 97
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','biotechnology','생물공학','n');
--행 98
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','obtain','획득하다','v');
--행 99
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','heal','치료하다','v');
--행 100
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','healer','의사','n');
--행 101
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','influence','영향','n');
--행 102
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','influential','영향력있는','a');
--행 103
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','critical','비평의,비판적인','a');
--행 104
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','critic','평론가','n');
--행 105
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','criticism','비평,비판','n');
--행 106
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','criticize','비평하다,비판하다','v');
--행 107
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','aware','깨닫고있는','a');
--행 108
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','unaware','깨닫지못하는','a');
--행 109
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','civil','시민의,공손한','a');
--행 110
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','civilian','시민','n');
--행 111
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','civility','공손','n');
--행 112
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','civic','시민의,도시의','a');
--행 113
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','civics','윤리학','n');
--행 114
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','civilization','문명','n');
--행 115
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','uncivilized','야만의','a');
--행 116
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','immediate','즉시의','a');
--행 117
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','material','원료','n');
--행 118
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','materialism','물질주의','n');
--행 119
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','materalistic','물질주의적인','a');
--행 120
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','nonmaterial','정신적인','a');
--행 121
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','male','수컷','n');
--행 122
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','compose','조직하다,작곡하다','v');
--행 123
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','composite','합성의','a');
--행 124
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','composer','작곡가','n');
--행 125
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','composition','조직,작곡','n');
--행 126
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','composure','진정','n');
--행 127
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','decompose','분해시키다','v');
--행 128
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','permit','허락하다','v');
--행 129
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','permission','허용','n');
--행 130
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','permissive','허용하는','a');
--행 131
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','advantage','유리','n');
--행 132
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','disadvantage','불리','n');
--행 133
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','vantage','우세','n');
--행 134
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','region','지역','n');
--행 135
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','insist','고집하다','v');
--행 136
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','conclude','결론을내리다','v');
--행 137
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','conclusion','결론','n');
--행 138
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','conclusive','결정적인','a');
--행 139
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','term','용어','n');
--행 140
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','approach','접근하다','v');
--행 141
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','desire','갈망하다','v');
--행 142
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','desirable','바람직한','a');
--행 143
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','desirous','바라는','a');
--행 144
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','undesirable','바람직스럽지못한','a');
--행 145
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','reduce','감소하다,축소하다','v');
--행 146
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','reduction','감소,축소','n');
--행 147
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','fuel','연료','n');
--행 148
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','conviction','신념','n');
--행 149
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','convict','유죄를선고하다','v');
--행 150
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','convince','납득시키다','v');
--행 151
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','unconvinced','납득되지않은','a');
--행 152
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','occupy','점령하다','v');
--행 153
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','occupation','점령','n');
--행 154
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','preoccupation','선점','n');
--행 155
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','unoccupied','소유자가없는','a');
--행 156
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','efficient','능률적인','a');
--행 157
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','inefficient','비능률적인','a');
--행 158
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','despite','～에도불구하고','prep');
--행 159
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','issue','논점','n');
--행 160
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','account','설명','n');
--행 161
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','accountant','회계사','n');
--행 162
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','unaccountable','설명할수없는','a');
--행 163
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','secretary','비서','n');
--행 164
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','secretarial','비서의','a');
--행 165
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','undersecretary','차관','n');
--행 166
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','firm','견고한','a');
--행 167
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','firmly','견고하게','ad');
--행 168
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','firmness','견고함','n');
--행 169
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','merely','단지','ad');
--행 170
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','mere','단지～에불과한','a');
--행 171
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','complex','복잡한','a');
--행 172
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','complexity','복잡성','n');
--행 173
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','complexion','안색','n');
--행 174
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','audience','청중','n');
--행 175
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','relieve','구하다','v');
--행 176
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','relief','구조','n');
--행 177
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','reliever','구조자','n');
--행 178
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','academic','학원의','a');
--행 179
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','academy','학원','n');
--행 180
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','academia','학계','n');
--행 181
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','horror','소름','n');
--행 182
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','horrible','소름끼치는','a');
--행 183
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','horrify','소름끼치게하다','v');
--행 184
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','threat','위협','n');
--행 185
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','threaten','위협하다','v');
--행 186
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','pure','순수한','a');
--행 187
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','purity','순수','n');
--행 188
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','purify','정화하다','v');
--행 189
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','impure','순수하지못한','a');
--행 190
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','mood','분위기','n');
--행 191
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','moody','변덕스러운','a');
--행 192
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','consume','소비하다','v');
--행 193
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','consumption','소비','n');
--행 194
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','explode','폭발시키다','v');
--행 195
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','explosion','폭발','n');
--행 196
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','explosive','폭발의','a');
--행 197
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','approve','승인하다','v');
--행 198
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','approval','승인','n');
--행 199
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','disapprove','승인하지않다','v');
--행 200
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','steady','안정된, 꾸준한','a');
--행 201
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','steadily','안정되게','ad');
--행 202
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','steadfastly','단호하게','ad');
--행 203
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','unsteadily','불안정하게','ad');
--행 204
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','moral','도덕적인','a');
--행 205
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','morality','도덕','n');
--행 206
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','immoral','부도덕한','a');
--행 207
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','psychology','심리학','n');
--행 208
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','psychic','영혼의','a');
--행 209
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','psycho','정신병자','n');
--행 210
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','psychologist','심리학자','n');
--행 211
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','psychiatrist','정신과','n');
--행 212
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','psychokinesis','염력','n');
--행 213
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','tide','조수','n');
--행 214
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','tidal','조수간만이있는','a');
--행 215
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','secure','안전한','a');
--행 216
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','security','안전','n');
--행 217
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','insecure','불안전한','a');
--행 218
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','witness','목격자','n');
--행 219
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','eyewitness','목격자','n');
--행 220
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','decrease','감소하다','v');
--행 221
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','guarantee','보증','n');
--행 222
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','guarantor','피보증인','n');
--행 223
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','shadow','그림자','n');
--행 224
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','frustrate','좌절시키다','v');
--행 225
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','pupil','개인','n');
--행 226
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','leisure','여가','n');
--행 227
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','leisurely','유유히','ad');
--행 228
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','annoy','성가시게굴다','v');
--행 229
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','portion','분배','n');
--행 230
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','client','의뢰인','n');
--행 231
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','expert','전문가','n');
--행 232
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','expertise','전문적기술','n');
--행 233
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','describe','묘사하다','v');
--행 234
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','describable','묘사할수있는','a');
--행 235
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','descriptive','묘사적인','a');
--행 236
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','description','묘사','n');
--행 237
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','indescribable','형언할수없는','a');
--행 238
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','duty','의무','n');
--행 239
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','dutiful','의무를다하는','a');
--행 240
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','define','정의를내리다','v');
--행 241
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','definite','정해진','a');
--행 242
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','definitive','결정적인','a');
--행 243
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','indefinite','한계가없는','a');
--행 244
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','undefined','정의되지않은','a');
--행 245
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','positive','긍정적인','a');
--행 246
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','participate','참가하다','v');
--행 247
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','participant','참가자','n');
--행 248
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','participation','참가','n');
--행 249
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','average','평균','n');
--행 250
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','publish','널리알리다','v');
--행 251
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','publication','발표','n');
--행 252
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','publisher','발표자','n');
--행 253
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','detail','세부사항','n');
--행 254
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','novel','소설','n');
--행 255
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','novelette','중편','n');
--행 256
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','novelty','색다름','n');
--행 257
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','novelist','소설가','n');
--행 258
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','oppose','반대하다','v');
--행 259
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','opposite','정반대의','a');
--행 260
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','opposition','반대','n');
--행 261
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','opponent','반대자','n');
--행 262
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','delight','기쁨','n');
--행 263
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','essential','본질적인','a');
--행 264
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','essence','본질,','n');
--행 265
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','brief','간결한','a');
--행 266
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','briefing','보고','n');
--행 267
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','brevity','간결함','n');
--행 268
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','intend','～할의도이다','v');
--행 269
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','intention','의도','n');
--행 270
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','intentional','의도적인','a');
--행 271
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','intent','의향','n');
--행 272
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','intently','골똘히','ad');
--행 273
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','unintentionally','무심코','ad');
--행 274
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','amaze','놀라게하다','v');
--행 275
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','balance','균형','n');
--행 276
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','unbalance','불균형','n');
--행 277
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','unbalanced','균형이잡히지않은','a');
--행 278
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','violent','폭력의','a');
--행 279
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','nonviolent','비폭력의','a');
--행 280
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','nonviolence','비폭력','n');
--행 281
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','arrange','배열하다','v');
--행 282
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','arrangement','배열','n');
--행 283
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','rearrange','재배열하다','v');
--행 284
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','lack','부족','n');
--행 285
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','struggle','투쟁하다','v');
--행 286
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','rely','신뢰하다','v');
--행 287
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','reliability','신뢰도','n');
--행 288
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','reliance','신뢰','n');
--행 289
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','unreliable','신뢰할수없는','a');
--행 290
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','revolution','혁명','n');
--행 291
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','revolve','회전하다','v');
--행 292
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','claim','요구하다','v');
--행 293
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','attempt','시도하다','v');
--행 294
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','injure','상처입히다','v');
--행 295
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','injury','상해','n');
--행 296
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','uninjured','상처입지않은','a');
--행 297
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','significant','중요한','a');
--행 298
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','signify','의미하다','v');
--행 299
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','significance','중요','n');
--행 300
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','insignificant','중요하지않은','a');
--행 301
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','seldom','거의～않다','ad');
--행 302
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','admit','허락하다','v');
--행 303
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','admission','허락','n');
--행 304
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','admittance','입장','n');
--행 305
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','grant','승인하다,수여하다','v');
--행 306
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','embarrass','당황케하다,쪼들리게하다','v');
--행 307
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','embarrassment','당황재정곤란','n');
--행 308
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','interrupt','가로막다','v');
--행 309
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','interruption','중단','n');
--행 310
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','uninterrupted','중단되지않은','a');
--행 311
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','pot','단지하나분량','n');
--행 312
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','pottery','도기류','n');
--행 313
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','potter','도공','n');
--행 314
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','repot','식물을다른화분에옮기다','v');
--행 315
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','decade','10개가묶인것,10년간','n');
--행 316
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','edge','가장자리','n');
--행 317
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','delay','늦추다','v');
--행 318
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','indicate','가리키다','v');
--행 319
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','indication','지시징후','n');
--행 320
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','error','오류','n');
--행 321
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','err','잘못하다','v');
--행 322
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','erroneous','잘못된','a');
--행 323
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','focus','초점','n');
--행 324
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','focal','초점의','a');
--행 325
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','bifocal','이중초점의','a');
--행 326
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','mental','마음의','a');
--행 327
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','mentality','마음','n');
--행 328
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','labor','노동','n');
--행 329
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','laborer','노동자','n');
--행 330
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','laborious','힘든','a');
--행 331
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','guilty','유죄의','a');
--행 332
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','guilt','죄','n');
--행 333
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','apologize','사과하다','v');
--행 334
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','apology','사과','n');
--행 335
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','mass','큰덩어리','n');
--행 336
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','mass-com','신문방송','n');
--행 337
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','massive','대규모의','a');
--행 338
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','feature','얼굴의생김새,특징','n');
--행 339
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','typical','전형적인,상징적인','a');
--행 340
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','capable','능력이있는','a');
--행 341
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','capability','능력','n');
--행 342
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','capacity','용량','n');
--행 343
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','incapable','무능한','a');
--행 344
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','accustom','익숙케','v');
--행 345
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','nevertheless','그럼에도','ad');
--행 346
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','agriculture','농업','n');
--행 347
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','minority','소수','n');
--행 348
INSERT INTO WORD (WORD_NO, WORD_LEVEL, WORD_ENG, WORD_KOR, WORD_PART) VALUES (WORD_NO_SEQ.NEXTVAL,'H','minor','소수의','a');
